repos:
  - repo: local
    hooks:
      - id: validate-package-metadata
        name: Validate Rayforge package metadata
        entry: python scripts/validate_package.py
        language: python
        # Run this hook only when the metadata file itself changes.
        files: ^rayforge-package\.yaml$
        # Ensure the script uses the same virtual environment.
        additional_dependencies: [pyyaml, semver]
