name: Announce New Release to Rayforge Registry

# This workflow triggers automatically whenever a new tag matching 'v*.*.*' is pushed.
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  announce-release:
    name: Announce to Central Registry
    runs-on: ubuntu-latest
    steps:
      - name: Send repository_dispatch event
        uses: peter-evans/repository-dispatch@v2
        with:
          # The central registry repository that will receive the announcement.
          # Do not change this value.
          repository: rayforge/rayforge-plugin-registry
          
          # This uses the secret you created in your repository settings.
          token: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
          
          # This is the event name the central registry is listening for.
          # Do not change this value.
          event-type: package-release-published
          
          # This is the data payload sent with the announcement.
          # It includes the tag that triggered the workflow and your repository name.
          client-payload: >-
            {
              "tag": "${{ github.ref_name }}",
              "repository": "${{ github.repository }}"
            }
